version: '3.8'

services:
  backend:
    build: ./backend
    container_name: crm-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=crmdb
      - JWT_SECRET=khjdfhksfhjksfdhkbdsfbhkdsf
      - META_API_KEY=b49e5e93725607d0b162a98b1fd2db46862bba4b63ede6b458fb361492a4cc55
    depends_on:
      - mysql
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: crm-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crmdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
