FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

COPY . .

EXPOSE 5000

CMD ["/wait-for.sh", "mysql", "3306", "node", "index.js"]
